### ISSUE TITLE
Larger 64bit RAMs fail in global or detailed routing 

### ISSUE THREAD

**Issue by antonblanchard** [AUCOHL/DFFRAM#109]
While we can build up 64 bit RAMs with 2 32 bit building blocks, it would be nice to have native 64 bit macros.

**Comment by donn** [comment]
We... do. Simply pass the size -s [word_count]x64. It's not supported by register files yet though.

**Comment by antonblanchard** [comment]
Thanks, I was just looking for a 64 bit RAM in this case. I now realise my repo is still pointing at Mohamed's repo. Closing.

**Comment by antonblanchard** [comment]
I tried `-s 512x64` and `-s 1024x64` and both failed in global routing. Is there anything else I need to tune?

**Comment by donn** [comment]
Some of the larger designs are buggy, I’d say try the donn/density_2 branch but I’m still working on them

**Comment by antonblanchard** [comment]
It looks like the `density_2` branch is now upstream. I haven't had any luck with `-s 512x64` or `-s 1024x64`. I tried reducing `global_routing_layer_adjustments` but couldn't get through both global and detailed routing

**Comment by donn** [comment]
Gotcha, I’ll take a look. Some designs that are too congested/not square enough just fail, so they might require halo adjustments or smth like that.

**Comment by antonblanchard** [comment]
Thanks for the pointer wrt halo. On the latest DFFRAM github I managed to get a `512x64` RAM to work with:

```./dffram.py -s 512x64 -H 200```

I also needed to be a bit more aggressive in global routing with:

```
-set global_routing_layer_adjustments {{met1 0.5} {met2 0.5} {met3 0.5} {met4 0.5}}
+set global_routing_layer_adjustments {{met1 0.3} {met2 0.3} {met3 0.3} {met4 0.3}}
```

![512x64](https://user-images.githubusercontent.com/2029971/140017221-0837b27c-f2ef-4b0d-bcc5-561cd328a582.png)

Apart from rearranging it to be more square (as you suggest), we could optimise this a bit more by having separate horizontal and vertical halo options - we don't need a horizontal halo in this example.

**Comment by donn** [comment]
You say that, but look how close the pins are even with such a huge horizontal halo...
