### ISSUE TITLE
Tracks on met5

### ISSUE THREAD

**Issue by antonblanchard** [AUCOHL/DFFRAM#111]
Looking at the output of `dffram.py -s 512x32`, I see one track on met5. We have a blockage on met5:

```
BLOCKAGES 1 ;
    - LAYER met5 RECT ( 0 0 ) ( 835820 786080 ) ;
END BLOCKAGES
```

But it appears to be too small, because we have a met5 track here:

```
      NEW met5 ( 148580 790500 ) ( 199180 * )
```

Shouldn't the met5 blockage match DIEAREA?

```
DIEAREA ( 0 0 ) ( 841340 791520 ) ;
```

**Comment by donn** [comment]
You’re right. That is weird. I’m guessing there’s an area calculation quirk somewhere. Sorry about that
