### ISSUE TITLE
Register file LVS difference caused by missing TIE?

### ISSUE THREAD

**Issue by mbalestrini** [AUCOHL/DFFRAM#124]
I built the 32x32 register file and I get unmatched nets on the LVS step, and I think it might caused by this line:
https://github.com/Cloud-V/DFFRAM/blob/b6754dc7df3e7a9c434f1d04885e906db1d8baa8/platforms/sky130A/sky130_fd_sc_hd/_building_blocks/rf/model.v#L75

Shouldn't the `.EN` be connected to a sky130_fd_sc_hd__conb_1.HI , instead of the direct value ```1`b1```?

**Comment by donn** [comment]
Uh, yes. Thank you for catching that, that's a weird oversight.

**Comment by donn** [comment]
Sorry for the wait, should be fixed now.
