### ISSUE TITLE
Could DFFRAM instead use latches rather than flip flops?

### ISSUE THREAD

**Issue by mithro** [AUCOHL/DFFRAM#140]
My understanding is that latches are much smaller than flip flops, which brings up the following questions. 

 * Is DFFRAM already using latches?
 * If not, could it use latches instead of flip flops?

**Comment by shalan** [comment]
DFFRAM Compiler supports both latches (default) and flip flops to implement the RAM.

**Comment by mithro** [comment]
I guess it probably should be called `DlatchRAM` ;-)? Have you talked to James Stine about potentially making an area optimized cell for primary DFFRAM usage?

**Comment by donn** [comment]
The name stuck. No, we haven't though.

**Comment by mithro** [comment]
DFFRAM is more catchy than DlatchRAM, so seems like a good decision to stick with it.
