### ISSUE TITLE
unknown compression method 'zstd'

### ISSUE THREAD

**Issue by b224hisl** [AUCOHL/DFFRAM#191]
Hello, I'm installing DFFRAM using the nix docker. (https://nixos.org/download.html#nix-install-docker)
And I followed the steps in https://github.com/AUCOHL/DFFRAM/blob/main/docs/Usage.md. 
But I met a problem when executing `nix-shell`, it reports `unknown compression method 'zstd'`, shown as:
![image](https://github.com/AUCOHL/DFFRAM/assets/39954153/b2532947-c8a2-4c8b-b90c-ab8e29364946)
I have highlighted my commands. So does anybody knowns how to handle this problems?

**Comment by b224hisl** [comment]
Actually, I have installed the zstd
![image](https://github.com/AUCOHL/DFFRAM/assets/39954153/873bbd7f-fbf4-4871-a3ce-2a55a8e9e4a3)

**Comment by donn** [comment]
Not really sure why this would happen. Are you sure you installed Nix using `sh <(curl -L https://nixos.org/nix/install) --daemon --yes` or did you `apk add nix`?

**Comment by b224hisl** [comment]
> Not really sure why this would happen. Are you sure you installed Nix using `sh <(curl -L https://nixos.org/nix/install) --daemon --yes` or did you `apk add nix`?

No because I use the nix docker so I think it should have nix
![image](https://github.com/AUCOHL/DFFRAM/assets/39954153/3c1e04a9-a0a5-4f90-9666-352d7d252a77)

**Comment by donn** [comment]
The Nix docker is not up-to-date. I'll kindly ask you to install Nix natively.

**Comment by b224hisl** [comment]
> The Nix docker is not up-to-date. I'll kindly ask you to install Nix natively.

Well maybe you are right. After giving up on using Nixdocker, I reinstalled Nix and that resolved the issue. Anyway thank you very much~ Now you can close this issue.

**Comment by donn** [comment]
Glad it worked!
