### ISSUE TITLE
Dual ported and single ported should have separate pin order config files.

### ISSUE THREAD

**Issue by ahmednofal** [AUCOHL/DFFRAM#95]

**Comment by apond308** [comment]
Is the dual port (2R1W) version working right now? I run "./dffram.py -s 32x32 -b sky130A:rf -v 2R1W" and am getting an error. Is this issue saying that dual port is not working?

**Comment by ahmednofal** [comment]
This seems to be the RF:register file. Try `-b sky130A:ram`

**Comment by donn** [comment]
Well, we typically refer to 1RW1R as "dual-ported memory" in this project, and 2R1W as register file. That said, yes, there appears to be a problem with this module. Apologies- we'll track it in #97

**Comment by apond308** [comment]
Great, thank you for the information. It looks like the merge fixed the problem.
