### ISSUE TITLE
String error in dffram.py

### ISSUE THREAD

**Issue by apond308** [AUCOHL/DFFRAM#96]
When running dffram.py, getting TypeError with string path for pdk_root:

File "./dffram.py", line 692, in flow
    prep(build_folder, pdk_root)
  File "./dffram.py", line 117, in prep
    pdk_root = os.path.abspath(os.path.realpath(local_pdk_root))
  File "/usr/lib/python3.8/posixpath.py", line 390, in realpath
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by apond308** [comment]
How do I do a pull request to make the change? I don't have permission.

**Comment by donn** [comment]
Hey apond, generally, when you want to make a PR to an organization you're not a member of, you start by forking the relevant repository (e.g. `apond308/DFFRAM`,) make the changes, then create "Open a Pull Request" there.

**Comment by apond308** [comment]
Great, thank you. I will go ahead and do that.

**Comment by apond308** [comment]
Issue addressed in pull request #106
